### ISSUE TITLE
more details 

### ISSUE THREAD

**Issue by rtty88** [jshbrntt/speed-monitor-pi#1]
could you please share more details about how to import the tool to raspberry 
I already did install all the requirements 
![image](https://github.com/jshbrntt/speed-monitor-pi/assets/96175987/f9f179c5-c244-4c82-b694-3d30422227aa)

**Comment by jshbrntt** [comment]
@rtty88 sorry if this wasn't clear but you're not supposed to clone these files directly onto a Rapsberry Pi, but instead supposed to install the project over SSH from another PC on the same local area network via the Ansible playbook running in a Docker container.
